WARNING 2021-01-22 16:25:35,962 log 11140 16904 Not Found: /
WARNING 2021-01-22 16:25:35,963 basehttp 11140 16904 "GET / HTTP/1.1" 404 2032
WARNING 2021-01-22 16:25:36,053 log 11140 16904 Not Found: /favicon.ico
WARNING 2021-01-22 16:25:36,053 basehttp 11140 16904 "GET /favicon.ico HTTP/1.1" 404 2083
ERROR 2021-01-22 17:25:34,849 log 20192 17256 Internal Server Error: /store/book/
Traceback (most recent call last):
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\rest_framework\viewsets.py", line 117, in view
    handler = getattr(self, action)
AttributeError: 'BookVeiwSet' object has no attribute 'create_Book'
ERROR 2021-01-22 17:25:34,852 basehttp 20192 17256 "GET /store/book/ HTTP/1.1" 500 75163
ERROR 2021-01-22 17:53:38,467 log 11836 21580 Internal Server Error: /store/book/3
Traceback (most recent call last):
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\Abi Blista\PycharmProjects\pythonProject\venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/store/book/3/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-01-22 17:53:38,468 basehttp 11836 21580 "PUT /store/book/3 HTTP/1.1" 500 68737
WARNING 2021-01-26 19:43:24,472 log 23236 11604 Not Found: /
WARNING 2021-01-26 19:43:24,473 basehttp 23236 11604 "GET / HTTP/1.1" 404 2032
WARNING 2021-01-26 19:43:24,544 log 23236 11604 Not Found: /favicon.ico
WARNING 2021-01-26 19:43:24,545 basehttp 23236 11604 "GET /favicon.ico HTTP/1.1" 404 2083
WARNING 2021-01-26 19:47:19,485 log 27140 18388 Method Not Allowed: /store/book/login/
WARNING 2021-01-26 19:47:19,486 basehttp 27140 18388 "GET /store/book/login/ HTTP/1.1" 405 40
ERROR 2021-01-26 19:47:25,786 log 27140 18388 Internal Server Error: /store/book/login
Traceback (most recent call last):
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/store/book/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-01-26 19:47:25,787 basehttp 27140 18388 "POST /store/book/login HTTP/1.1" 500 68307
ERROR 2021-01-26 19:48:00,901 log 27140 20964 Internal Server Error: /store/book/login
Traceback (most recent call last):
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/store/book/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2021-01-26 19:48:00,902 basehttp 27140 20964 "POST /store/book/login HTTP/1.1" 500 68818
ERROR 2021-01-26 19:53:08,234 log 13112 24012 Internal Server Error: /store/book/login/
Traceback (most recent call last):
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Abi Blista\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2021-01-26 19:53:08,235 basehttp 13112 24012 "POST /store/book/login/ HTTP/1.1" 500 78089
WARNING 2021-01-26 19:56:11,182 log 3076 17168 Not Found: /store/book/login/
WARNING 2021-01-26 19:56:11,183 basehttp 3076 17168 "POST /store/book/login/ HTTP/1.1" 404 31
WARNING 2021-01-26 19:57:31,974 log 3076 17168 Not Found: /store/book/login/
WARNING 2021-01-26 19:57:31,974 basehttp 3076 17168 "POST /store/book/login/ HTTP/1.1" 404 31
WARNING 2021-01-26 19:58:02,170 log 3076 17168 Not Found: /store/book/login/
WARNING 2021-01-26 19:58:02,171 basehttp 3076 17168 "POST /store/book/login/ HTTP/1.1" 404 42
WARNING 2021-02-02 18:31:40,951 log 19324 14224 Not Found: /
WARNING 2021-02-02 18:31:40,951 basehttp 19324 14224 "GET / HTTP/1.1" 404 2032
WARNING 2021-02-02 18:31:41,003 log 19324 14224 Not Found: /favicon.ico
WARNING 2021-02-02 18:31:41,004 basehttp 19324 14224 "GET /favicon.ico HTTP/1.1" 404 2083
ERROR 2021-02-02 18:36:19,713 exception 19324 2132 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:36:19,773 log 19324 2132 Bad Request: /
WARNING 2021-02-02 18:36:19,774 basehttp 19324 2132 "GET / HTTP/1.1" 400 68022
ERROR 2021-02-02 18:36:19,941 exception 19324 9796 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:36:19,963 log 19324 9796 Bad Request: /favicon.ico
WARNING 2021-02-02 18:36:19,964 basehttp 19324 9796 "GET /favicon.ico HTTP/1.1" 400 68521
ERROR 2021-02-02 18:36:19,983 exception 19324 13924 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:36:20,004 log 19324 13924 Bad Request: /
WARNING 2021-02-02 18:36:20,005 basehttp 19324 13924 "GET / HTTP/1.1" 400 68612
ERROR 2021-02-02 18:36:21,772 exception 19324 8448 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:36:21,787 log 19324 8448 Bad Request: /favicon.ico
WARNING 2021-02-02 18:36:21,788 basehttp 19324 8448 "GET /favicon.ico HTTP/1.1" 400 68521
ERROR 2021-02-02 18:36:33,929 exception 19324 19296 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:36:33,947 log 19324 19296 Bad Request: /store/book/
WARNING 2021-02-02 18:36:33,947 basehttp 19324 19296 "GET /store/book/ HTTP/1.1" 400 68582
ERROR 2021-02-02 18:36:35,099 exception 19324 17680 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:36:35,120 log 19324 17680 Bad Request: /favicon.ico
WARNING 2021-02-02 18:36:35,121 basehttp 19324 17680 "GET /favicon.ico HTTP/1.1" 400 68532
ERROR 2021-02-02 18:37:28,594 exception 18252 5920 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:37:28,628 log 18252 5920 Bad Request: /store/book/
WARNING 2021-02-02 18:37:28,629 basehttp 18252 5920 "GET /store/book/ HTTP/1.1" 400 68280
ERROR 2021-02-02 18:37:29,381 exception 18252 15380 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:37:29,400 log 18252 15380 Bad Request: /store/book/
WARNING 2021-02-02 18:37:29,400 basehttp 18252 15380 "GET /store/book/ HTTP/1.1" 400 68744
ERROR 2021-02-02 18:37:30,545 exception 18252 12460 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:37:30,562 log 18252 12460 Bad Request: /favicon.ico
WARNING 2021-02-02 18:37:30,562 basehttp 18252 12460 "GET /favicon.ico HTTP/1.1" 400 68093
ERROR 2021-02-02 18:38:25,661 exception 16364 20012 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:38:25,699 log 16364 20012 Bad Request: /store/book/
WARNING 2021-02-02 18:38:25,699 basehttp 16364 20012 "GET /store/book/ HTTP/1.1" 400 68881
ERROR 2021-02-02 18:38:26,860 exception 16364 12940 Invalid HTTP_HOST header: '2aa3a031474a.ngrok.io'. You may need to add '2aa3a031474a.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:38:26,894 log 16364 12940 Bad Request: /favicon.ico
WARNING 2021-02-02 18:38:26,895 basehttp 16364 12940 "GET /favicon.ico HTTP/1.1" 400 68358
ERROR 2021-02-02 18:40:50,122 exception 16364 21868 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:40:50,144 log 16364 21868 Bad Request: /store/book/
WARNING 2021-02-02 18:40:50,145 basehttp 16364 21868 "GET /store/book/ HTTP/1.1" 400 68143
ERROR 2021-02-02 18:40:50,349 exception 16364 11648 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:40:50,365 log 16364 11648 Bad Request: /favicon.ico
WARNING 2021-02-02 18:40:50,365 basehttp 16364 11648 "GET /favicon.ico HTTP/1.1" 400 68093
ERROR 2021-02-02 18:40:50,403 exception 16364 19340 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:40:50,420 log 16364 19340 Bad Request: /store/book/
WARNING 2021-02-02 18:40:50,420 basehttp 16364 19340 "GET /store/book/ HTTP/1.1" 400 68744
ERROR 2021-02-02 18:40:52,420 exception 16364 3588 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:40:52,436 log 16364 3588 Bad Request: /favicon.ico
WARNING 2021-02-02 18:40:52,437 basehttp 16364 3588 "GET /favicon.ico HTTP/1.1" 400 68093
WARNING 2021-02-02 18:41:12,734 log 16364 12176 Not Found: /
WARNING 2021-02-02 18:41:12,734 basehttp 16364 12176 "GET / HTTP/1.1" 404 2032
ERROR 2021-02-02 18:41:27,543 exception 16364 17068 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:41:27,561 log 16364 17068 Bad Request: /store/book/
WARNING 2021-02-02 18:41:27,561 basehttp 16364 17068 "GET /store/book/ HTTP/1.1" 400 68719
ERROR 2021-02-02 18:41:29,000 exception 16364 3844 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:41:29,067 log 16364 3844 Bad Request: /favicon.ico
WARNING 2021-02-02 18:41:29,068 basehttp 16364 3844 "GET /favicon.ico HTTP/1.1" 400 68093
ERROR 2021-02-02 18:42:20,257 exception 12116 1872 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:42:20,280 log 12116 1872 Bad Request: /store/book/
WARNING 2021-02-02 18:42:20,280 basehttp 12116 1872 "GET /store/book/ HTTP/1.1" 400 68280
ERROR 2021-02-02 18:42:20,781 exception 12116 20292 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:42:20,797 log 12116 20292 Bad Request: /store/book/
WARNING 2021-02-02 18:42:20,797 basehttp 12116 20292 "GET /store/book/ HTTP/1.1" 400 68744
ERROR 2021-02-02 18:42:22,258 exception 12116 14596 Invalid HTTP_HOST header: '5a0cf98d48b7.ngrok.io'. You may need to add '5a0cf98d48b7.ngrok.io' to ALLOWED_HOSTS.
WARNING 2021-02-02 18:42:22,286 log 12116 14596 Bad Request: /favicon.ico
WARNING 2021-02-02 18:42:22,286 basehttp 12116 14596 "GET /favicon.ico HTTP/1.1" 400 68093
WARNING 2021-02-02 18:46:28,495 log 15960 13416 Not Found: /
WARNING 2021-02-02 18:46:28,496 basehttp 15960 13416 "GET / HTTP/1.1" 404 2032
WARNING 2021-02-02 18:47:29,738 log 17088 8092 Not Found: /favicon.ico
WARNING 2021-02-02 18:47:29,739 basehttp 17088 8092 "GET /favicon.ico HTTP/1.1" 404 2090
WARNING 2021-02-02 18:48:36,541 log 17088 3224 Not Found: /robots.txt
WARNING 2021-02-02 18:48:36,541 basehttp 17088 3224 "GET /robots.txt HTTP/1.1" 404 2087
WARNING 2021-02-02 18:48:40,061 log 17088 22324 Not Found: /favicon.ico
WARNING 2021-02-02 18:48:40,061 basehttp 17088 22324 "GET /favicon.ico HTTP/1.1" 404 2090
WARNING 2021-02-02 18:48:54,435 log 17088 21580 Not Found: /favicon.ico
WARNING 2021-02-02 18:48:54,436 basehttp 17088 21580 "GET /favicon.ico HTTP/1.1" 404 2090
WARNING 2021-02-02 18:49:02,266 log 17088 5504 Not Found: /favicon.ico
WARNING 2021-02-02 18:49:02,266 basehttp 17088 5504 "GET /favicon.ico HTTP/1.1" 404 2090
